services:
  backend:
    container_name: fastapi-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    container_name: nextjs-frontend
    build:
      context: ./frontend/
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    restart: always

  db:
    container_name: postgres-db
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    restart: always

volumes:
  postgres_data:
    driver: local
