# version: "3.8"

# services:
#   backend:
#     container_name: fastapi-backend
#     build:
#       context: ./backend
#       dockerfile: dockerfile
#     ports:
#       - "8000:8000"
#     env_file:
#       - ./backend/.env
#     depends_on:
#       - db
#     volumes: -./backend:/app
#     restart: always

#   frontend:
#     container_name: nextjs-frontend
#     build:
#       context: ./frontend/todo-app
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     env_file:
#       - ./frontend/todo-app/.env
#     depends_on:
#       - backend
#     volumes:
#       - ./frontend/todo-app:/frontend
#       - /frontend/node_modules
#     restart: always

#   db:
#     container_name: postgres-db
#     image: postgres:15
#     ports:
#       - "5432:5432"
#     env_file:
#       - ./db/.env
#     volumes:
#       - postgres_data:/var/lib/postgresql/postgres_data
#     restart: always

#   volumes:
#     postgres_data:
#       driver: local
