FROM python:3.10

WORKDIR /app

# Install netcat (for wait-for-db.sh to work)

RUN apt-get update && apt-get install -y netcat-openbsd

# COPY requirements.txt .

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

# copy to wait for the db to load

COPY wait-for-db.sh /app/wait-for-db.sh

RUN chmod +x /app/wait-for-db.sh



# Use the wait-for-db.sh script to wait for the DB and then start uvicorn
CMD ["/app/wait-for-db.sh"]